afa-forsakring-fou/github-actions

- .github/workflows/main.yaml
Link Azure Devops: AB#12631
Description:
> Do submodule check in sonarjob also

- .github/workflows/actions/error-step/action.yaml
- .github/workflows/actions/gitignore-check/action.yaml
- .github/workflows/actions/submodule-check/action.yaml
- .github/workflows/main.yaml
Link Azure Devops: AB#12657
Description:
> add check for important line in gitignore

- .github/workflows/actions/gitignore-check/action.yaml
Link Azure Devops: AB#12657
Description:
> Add missing '!'

- .github/workflows/actions/submodule-check/action.yaml
Link Azure Devops: AB#12631
Description:
> Fix correct logic with check for submodule

- .github/workflows/actions/submodule-check/action.yaml
Link Azure Devops: AB#12631
Description:
> Remove double !

- .github/workflows/actions/submodule-check/action.yaml
Link Azure Devops: [AB#13775](https://afaforsakring.visualstudio.com/3994b3a7-ce7a-43d7-ab03-6cfb35e32ac4/_workitems/edit/13775)
Description:
> Update check for latest shared tools

- .github/workflows/approved.yaml
- .github/workflows/main.yaml
- .github/workflows/rebase.yaml
Link Azure Devops: [AB#12876](https://afaforsakring.visualstudio.com/3994b3a7-ce7a-43d7-ab03-6cfb35e32ac4/_workitems/edit/12876)
Description:
> Set timout on all our jobs

- .github/workflows/actions/react/action.yaml
- .github/workflows/actions/react/sonarcloud/action.yaml
- .github/workflows/actions/react/yarn-cache/action.yaml
- .github/workflows/main.yaml
Link Azure Devops: [AB#13846](https://afaforsakring.visualstudio.com/3994b3a7-ce7a-43d7-ab03-6cfb35e32ac4/_workitems/edit/13846)
Description:
> set output ->  $GITHUB_OUTPUT and update sonar to 1.7

- .github/workflows/actions/react/yarn-cache/action.yaml
Link Azure Devops: [AB#14268](https://afaforsakring.visualstudio.com/3994b3a7-ce7a-43d7-ab03-6cfb35e32ac4/_workitems/edit/14268)
Description:
> check version of yarn and use right command

- .github/workflows/main.yaml
Link Azure Devops: [AB#14567](https://afaforsakring.visualstudio.com/3994b3a7-ce7a-43d7-ab03-6cfb35e32ac4/_workitems/edit/14567)
Description:
> fix concurrency issue with main ref

- .github/workflows/actions/dotnet/sonarcloud/action.yaml
Link Azure Devops: AB#
Description:
> changes to afaforsakring2 for sonar

- .github/workflows/main.yaml
Link Azure Devops: AB#
Description:
> Removed sonarcloud step

- .github/workflows/actions/react/action.yaml
Link Azure Devops: [AB#245928](https://dev.azure.com/afaforsakring2/e7b57587-8481-4413-8ea1-c5738c13c364/_workitems/edit/245928)
Description:
> yarn lint som ett eget steg

- .github/workflows/actions/react/action.yaml
Link Azure Devops: [AB#245928](https://dev.azure.com/afaforsakring2/e7b57587-8481-4413-8ea1-c5738c13c364/_workitems/edit/245928)
Description:
> lägg till GIT_TOKEN i yarn lint

- .github/workflows/actions/dotnet/action.yaml
- .github/workflows/actions/dotnet/restore/action.yaml
- .github/workflows/main.yaml
Link Azure Devops: [AB#253007](https://dev.azure.com/afaforsakring2/e7b57587-8481-4413-8ea1-c5738c13c364/_workitems/edit/253007)
Description:
> skicka med token för Azure devops

- .github/workflows/main.yaml
Link Azure Devops: [AB#253007](https://dev.azure.com/afaforsakring2/e7b57587-8481-4413-8ea1-c5738c13c364/_workitems/edit/253007)
Description:
> skicka token till Docker build m.m.

- .github/workflows/main.yaml
Link Azure Devops: [AB#261122](https://dev.azure.com/afaforsakring2/e7b57587-8481-4413-8ea1-c5738c13c364/_workitems/edit/261122)
Description:
> ta bort ref

- .github/workflows/actions/react/action.yaml
- .github/workflows/actions/react/setup-node/action.yaml
- .github/workflows/main.yaml
Link Azure Devops: [AB#265563](https://dev.azure.com/afaforsakring2/e7b57587-8481-4413-8ea1-c5738c13c364/_workitems/edit/265563)
Description:
> Corepack enable

- .github/workflows/actions/dotnet/action.yaml
- .github/workflows/actions/dotnet/dotnet-cache/action.yaml
- .github/workflows/actions/dotnet/setup-dotnet/action.yaml
- .github/workflows/main.yaml
Link Azure Devops: [AB#271666](https://dev.azure.com/afaforsakring2/e7b57587-8481-4413-8ea1-c5738c13c364/_workitems/edit/271666)
Description:
> Actions v4

- .github/workflows/main.yaml
Link Azure Devops: [AB#273288](https://dev.azure.com/afaforsakring2/e7b57587-8481-4413-8ea1-c5738c13c364/_workitems/edit/273288)
Description:
> Validera yaml i pipelines

- .github/workflows/actions/react/action.yaml
- .github/workflows/main.yaml
Link Azure Devops: [AB#281513](https://dev.azure.com/afaforsakring2/e7b57587-8481-4413-8ea1-c5738c13c364/_workitems/edit/281513)
Description:
> ta bort HASURA_URL och X_HASURA_ADMIN_SECRET

- .github/workflows/actions/react/action.yaml
- .github/workflows/main.yaml
Link Azure Devops: [AB#275788](https://dev.azure.com/afaforsakring2/e7b57587-8481-4413-8ea1-c5738c13c364/_workitems/edit/275788)
Description:
> ta bort Cypress-variabel
